# Generated by Django 5.2.10 on 2026-01-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='ten_khach', max_length=100)),
                ('customer_phone', models.CharField(db_column='sdt', max_length=15)),
                ('booking_time', models.DateTimeField(db_column='thoi_gian_dat')),
                ('guest_count', models.IntegerField(db_column='so_nguoi', default=1)),
                ('note', models.TextField(blank=True, db_column='ghi_chu', null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận')], db_column='trang_thai', default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='id_danhmuc', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ten_danhmuc', max_length=100)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_donhang', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(db_column='tong_tien', default=0)),
                ('status', models.CharField(db_column='trang_thai_tt', default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(db_column='id_ban', primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='so_ban', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Trống'), ('reserved', 'Đã đặt'), ('occupied', 'Đang dùng')], db_column='trang_thai', default='available', max_length=20)),
                ('reserved_at', models.DateTimeField(blank=True, db_column='thoi_gian_dat', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_column='thoi_gian_het_han', null=True)),
            ],
            options={
                'db_table': 'tables',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(db_column='id_mon', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ten_mon', max_length=255)),
                ('price', models.IntegerField(db_column='gia')),
                ('image', models.ImageField(blank=True, db_column='hinh_anh', null=True, upload_to='menu/')),
                ('category', models.ForeignKey(db_column='id_danhmuc', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='EMENU.category')),
            ],
            options={
                'verbose_name': 'Món ăn',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id_chitiet', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='so_luong', default=1)),
                ('note', models.TextField(blank=True, db_column='ghi_chu', null=True)),
                ('is_served', models.BooleanField(db_column='da_ra_mon', default=False)),
                ('item', models.ForeignKey(db_column='id_mon', on_delete=django.db.models.deletion.CASCADE, to='EMENU.item')),
                ('order', models.ForeignKey(db_column='id_donhang', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='EMENU.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(db_column='id_tt', primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('banking', 'CK')], db_column='phuong_thuc', max_length=20)),
                ('amount', models.IntegerField(db_column='so_tien', default=0)),
                ('paid_at', models.DateTimeField(auto_now_add=True, db_column='thoi_gian_tt')),
                ('order', models.ForeignKey(db_column='id_donhang', on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='EMENU.order')),
            ],
            options={
                'db_table': 'revenues',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(db_column='id_ban', on_delete=django.db.models.deletion.CASCADE, to='EMENU.table'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EMENU.table')),
            ],
        ),
    ]
